import React, { Component } from "react";
import * as _ from "lodash";
import "./sidebar.scss";
export class Sidebar extends Component {
  render() {
    return (
      <div className="sidebar-component">
        <ul>
          {_.values(categoryObj).map((x: any, index) => {
            return (
              <li
                key={index}
                className={
                  index == 1
                    ? "btn_primary_background btn_primary_text"
                    : "text-normal"
                }
              >
                {x.name}
              </li>
            );
          })}
        </ul>
      </div>
    );
  }
}

export default Sidebar;

const categoryObj = {
  "1": {
    id: 1,
    store_id: 2,
    name: "Nibbles",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 2,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 1,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-1-1-med_res.jpg",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-1-1-med_res.jpg",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-1-1-med_res.jpg",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-1-1-med_res.jpg",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: "a:0:{}",
    reporting_category_id: 1,
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 2,
    attribute_groups: {
      size: 1,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
        "18": 0,
        "19": 0,
      },
    },
    products: [1, 2, 3, 4],
    deals: [],
  },
  "2": {
    id: 2,
    store_id: 2,
    name: "Share Platters",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 1,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 2,
    allow_instruction: 1,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-2-0-placeholder.jpg?ver=1568771919",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-2-0-low_res.jpg?ver=1568771919",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-2-0-med_res.jpg?ver=1568771919",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-2-0-high_res.jpg?ver=1568771919",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: 0,
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 2,
    attribute_groups: {
      size: 1,
      toppings: 0,
      other: {
        "3": 1,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
      },
    },
    products: [7, 8, 9, 10],
    deals: [],
  },
  "3": {
    id: 3,
    store_id: 0,
    name: "From The Grill ",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 3,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-3-0-placeholder.jpg?ver=1568771919",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-3-0-low_res.jpg?ver=1568771919",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-3-0-med_res.jpg?ver=1568771919",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-3-0-high_res.jpg?ver=1568771919",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: 0,
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 3,
    attribute_groups: {
      size: 1,
      toppings: 0,
      other: {
        "3": 0,
        "4": 1,
        "5": 1,
        "6": 1,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
      },
    },
    products: [11, 12, 13, 14],
    deals: [],
  },
  "4": {
    id: 4,
    store_id: 0,
    name: "Burgers & Sandwiches",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 4,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "jpg",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-4-0-placeholder.jpg?ver=1568771919",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-4-0-low_res.jpg?ver=1568771919",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-4-0-med_res.jpg?ver=1568771919",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-4-0-high_res.jpg?ver=1568771919",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: 0,
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 4,
    attribute_groups: {
      size: 1,
      toppings: 16,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
      },
    },
    products: [15, 16, 17, 18, 19, 20],
    deals: [],
  },
  "5": {
    id: 5,
    store_id: 2,
    name: "Pizza",
    subtitle: "",
    swift_cat: 0,
    description:
      "All pizzas are made on a tomato base and topped with our house cheese blend",
    category_type: 2,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 5,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-5-0-placeholder.jpg?ver=1568771919",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-5-0-low_res.jpg?ver=1568771919",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-5-0-med_res.jpg?ver=1568771919",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-5-0-high_res.jpg?ver=1568771919",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: 0,
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 5,
    attribute_groups: {
      size: 2,
      toppings: 7,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 1,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
      },
    },
    products: [21, 22, 23, 24, 25, 27, 28],
    deals: [],
  },
  "6": {
    id: 6,
    store_id: 2,
    name: "Pasta",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 2,
    active: 1,
    menu_id: 1,
    forsale: 0,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 6,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-6-0-placeholder.jpg?ver=1568771920",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-6-0-low_res.jpg?ver=1568771920",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-6-0-med_res.jpg?ver=1568771920",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-6-0-high_res.jpg?ver=1568771920",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: 0,
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 6,
    attribute_groups: {
      size: 1,
      toppings: 9,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 1,
        "12": 0,
        "13": 0,
        "14": 0,
      },
    },
    products: [30, 31, 32, 33, 34, 35],
    deals: [],
  },
  "7": {
    id: 7,
    store_id: 2,
    name: "Sides",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 7,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-7-0-placeholder.jpg?ver=1568771920",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-7-0-low_res.jpg?ver=1568771920",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-7-0-med_res.jpg?ver=1568771920",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-7-0-high_res.jpg?ver=1568771920",
    },
    lead_time: 0,
    perrow: 0,
    preptime_category_id: 1,
    print_groupid: "a:0:{}",
    reporting_category_id: 0,
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 7,
    attribute_groups: {
      size: 1,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
        "18": 0,
        "19": 0,
      },
    },
    products: [36, 37, 38, 39],
    deals: [],
  },
  "8": {
    id: 8,
    store_id: 2,
    name: "Sweet Ending",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 8,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-8-0-placeholder.jpg?ver=1568771920",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-8-0-low_res.jpg?ver=1568771920",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-8-0-med_res.jpg?ver=1568771920",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-8-0-high_res.jpg?ver=1568771920",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: 0,
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 8,
    attribute_groups: {
      size: 1,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
      },
    },
    products: [40, 41, 42, 43],
    deals: [],
  },
  "9": {
    id: 9,
    store_id: 0,
    name: "On Tap",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 9,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "jpg",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-9-0-placeholder.jpg?ver=1568771920",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-9-0-low_res.jpg?ver=1568771920",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-9-0-med_res.jpg?ver=1568771920",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-9-0-high_res.jpg?ver=1568771920",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: 0,
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 9,
    attribute_groups: {
      size: 11,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 1,
        "13": 0,
        "14": 0,
      },
    },
    products: [44, 45, 46, 47, 48, 49, 50, 51],
    deals: [],
  },
  "10": {
    id: 10,
    store_id: 2,
    name: "Bottled Drinks",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 1,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 10,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-10-0-placeholder.jpg?ver=1568771920",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-10-0-low_res.jpg?ver=1568771920",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-10-0-med_res.jpg?ver=1568771920",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-10-0-high_res.jpg?ver=1568771920",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: "a:0:{}",
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 10,
    attribute_groups: {
      size: 11,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
        "18": 0,
        "19": 0,
      },
    },
    products: [52, 53, 54, 55, 56, 57, 58, 59, 60, 61],
    deals: [],
  },
  "11": {
    id: 11,
    store_id: 2,
    name: "Wine",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 1,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 11,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-11-0-placeholder.jpg?ver=1568771920",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-11-0-low_res.jpg?ver=1568771920",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-11-0-med_res.jpg?ver=1568771920",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-11-0-high_res.jpg?ver=1568771920",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: "a:0:{}",
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 11,
    attribute_groups: {
      size: 11,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 1,
        "14": 0,
        "18": 0,
        "19": 0,
      },
    },
    products: [62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73],
    deals: [],
  },
  "12": {
    id: 12,
    store_id: 2,
    name: "Spirits",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 2,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 1,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 12,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-12-0-placeholder.jpg?ver=1568771921",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-12-0-low_res.jpg?ver=1568771921",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-12-0-med_res.jpg?ver=1568771921",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-12-0-high_res.jpg?ver=1568771921",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: "a:0:{}",
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 12,
    attribute_groups: {
      size: 11,
      toppings: 15,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 1,
        "18": 0,
        "19": 0,
      },
    },
    products: [74, 75, 76, 77, 78, 79],
    deals: [],
  },
  "13": {
    id: 13,
    store_id: 0,
    name: "Soft Drink & Juice",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 13,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "jpg",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-13-0-placeholder.jpg?ver=1568771921",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-13-0-low_res.jpg?ver=1568771921",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-13-0-med_res.jpg?ver=1568771921",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-13-0-high_res.jpg?ver=1568771921",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: 0,
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 13,
    attribute_groups: {
      size: 11,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 1,
      },
    },
    products: [80, 81, 82, 83, 85, 86, 87],
    deals: [],
  },
  "14": {
    id: 14,
    store_id: 2,
    name: "Beverages",
    subtitle: "",
    swift_cat: 0,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis posuere diam, nec dictum sapien. Nulla vitae turpis urna. Donec vel nunc elementum, fringilla quam eu, iaculis ipsum.",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [10, 11, 12],
    category_id: 14,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: {
      uploaded: {
        placeholder: true,
        low_res: true,
        med_res: true,
        high_res: true,
      },
      placeholder:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-14-0-placeholder.jpg?ver=1568771921",
      low_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-14-0-low_res.jpg?ver=1568771921",
      med_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-14-0-med_res.jpg?ver=1568771921",
      high_res:
        "https://d1uz2kmrg3qq0r.cloudfront.net/hoteldemo.orderup.com.au/images/default/category/category-14-0-high_res.jpg?ver=1568771921",
    },
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: "a:0:{}",
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 14,
    attribute_groups: {
      size: 11,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
        "18": 0,
        "19": 0,
      },
    },
    products: [88, 89, 90, 91, 92, 93, 94, 95, 96, 97],
    deals: [],
  },
  "16": {
    id: 16,
    store_id: 0,
    name: "FOR GOOGLE ANALYTICS",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 1,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 16,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: [],
    lead_time: 0,
    perrow: 0,
    preptime_category_id: 0,
    print_groupid: "a:0:{}",
    reporting_category_id: 0,
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 15,
    attribute_groups: {
      size: 17,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
        "18": 1,
        "19": 1,
      },
    },
    products: [98, 99, 100, 101, 102, 103, 104],
    deals: [],
  },
  "17": {
    id: 17,
    store_id: 0,
    name: "Goldilocks Delivery",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 2,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 0,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 17,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: [],
    lead_time: "",
    perrow: 0,
    preptime_category_id: "",
    print_groupid: "a:0:{}",
    reporting_category_id: "",
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 2,
    attribute_groups: {
      size: 1,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
        "18": 0,
        "19": 0,
      },
    },
    products: [105, 106, 107, 108, 109, 110],
    deals: [],
  },
  "18": {
    id: 18,
    store_id: 0,
    name: "Fixed Price Deals",
    subtitle: "",
    swift_cat: 0,
    description: "",
    category_type: 3,
    active: 1,
    menu_id: 1,
    forsale: 1,
    subcategory: 0,
    include_pickup: 1,
    include_delivery: 1,
    include_dinein: 1,
    include_roomservice: 1,
    is_subcategory: 0,
    sub_categories: [],
    category_id: 18,
    allow_instruction: 0,
    availability:
      'a:7:{i:0;a:1:{s:6:"active";i:1;}i:1;a:1:{s:6:"active";i:1;}i:2;a:1:{s:6:"active";i:1;}i:3;a:1:{s:6:"active";i:1;}i:4;a:1:{s:6:"active";i:1;}i:5;a:1:{s:6:"active";i:1;}i:6;a:1:{s:6:"active";i:1;}}',
    image_type: "",
    images: [],
    lead_time: "",
    perrow: 0,
    preptime_category_id: 0,
    print_groupid: "a:0:{}",
    reporting_category_id: 0,
    thumbsizes: 0,
    thumbsizesmobile: 0,
    order: 1,
    attribute_groups: {
      size: 0,
      toppings: 0,
      other: {
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "8": 0,
        "10": 0,
        "12": 0,
        "13": 0,
        "14": 0,
        "18": 0,
        "19": 0,
      },
    },
    products: [],
    deals: [3, 4, 5, 6],
  },
};
